### ISSUE TITLE
linear_regression_one_feature_using_mini_batch_with_tensorboard.py is not valid

### ISSUE THREAD

**Issue by anandanand84** [nethsix/gentle_tensorflow#7]
There is some issue with this file. Training doesnt provide intented results. I see the actual b value is 10.

**Comment by nethsix** [comment]
Thanks for testing it out. If you plot out the b vs train step number, or observe the output of running the script, that you will notice that b is still increasing albeit slowly with each train step. One way to make learning faster is to increase the 'learn_rate'.

Try setting 'learn_rate = 0.001'. Or set 'steps' to higher (but this takes a longer time). 

Setting the `learn_rate` higher does not always work because it may take too big a step and overshoot the minimum. One way to avoid this is to vary the `learn_rate` as the `cost` gets lower, i.e., take big steps when we are far away, and smaller ones as we are approaching the minimum.

**Comment by nethsix** [comment]
I've updated the script in the repo with 'learn_rate = 0.001'. It will be useful for others who try it.
